package com.emi.api;

import java.util.List;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.emi.dto.Employee;
import com.emi.exception.ApplicationException;
import com.emi.service.EmployeeService;

import jakarta.validation.Valid;

@RestController
@RequestMapping("/employees")
public class EmployeeApi {
	
	
	private EmployeeService employeeService;
	
	
	public EmployeeApi(EmployeeService employeeService) {
		super();
		this.employeeService = employeeService;
	}
	
	@GetMapping(value="/test" , produces= {"application/xml", "application/json"})
	public Employee test() {
		return new Employee(1, "John Doe", "123 Main St", 50000);
	}
	
	@GetMapping(produces= {"application/xml", "application/json"})
	public List<Employee> getEmployees() {
		return employeeService.getAllEmployees();
	}
	
	//using @requestbody to get the employee data from the http response generated by the client
	//UI(user input info) -> http request(info in the body in xml format) -> @requestbody (map the xml data to employee object)
	@PostMapping(produces={"application/json"}, consumes={"application/xml"})
	public List<Employee> addEmployee(@Valid @RequestBody Employee emp){
		return employeeService.addEmployee(emp);
	}
	@GetMapping(value="/{Id}" , produces= {"application/json"})
	public Employee getById(@PathVariable("Id") int id) {
		return employeeService.getAllEmployees().stream()
				.filter(e->e.getEmpId()==id)
				.findFirst()            
				.orElseThrow(()->new ApplicationException("Employee not found with id: "+id));
		         //Exception will be handled in GlobalException class
	}

}
